# Generated by Django 4.2.7 on 2023-11-08 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ramos',
            fields=[
                ('idRamo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=25)),
                ('carrera', models.CharField(max_length=20)),
                ('descripcion', models.CharField(max_length=40)),
                ('creditos', models.IntegerField(max_length=11)),
                ('horas', models.IntegerField(max_length=11)),
                ('sala', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'ramos',
            },
        ),
    ]
