# Generated by Django 4.2.7 on 2023-11-08 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formularioRamos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ramos',
            name='creditos',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='ramos',
            name='horas',
            field=models.IntegerField(),
        ),
    ]
