# Generated by Django 4.2.6 on 2023-11-18 20:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('formularioProfesor', '0001_initial'),
        ('formularioRamos', '0002_alter_ramos_creditos_alter_ramos_horas'),
    ]

    operations = [
        migrations.AddField(
            model_name='ramos',
            name='profesor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ramos', to='formularioProfesor.profesor'),
        ),
    ]
