# Generated by Django 4.2.6 on 2023-11-18 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formularioRamos', '0002_alter_ramos_creditos_alter_ramos_horas'),
        ('alumno', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumno',
            name='ramos',
            field=models.ManyToManyField(related_name='alumnos', to='formularioRamos.ramos'),
        ),
    ]
