# Generated by Django 4.2.6 on 2023-11-18 21:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('formularioRamos', '0003_ramos_profesor'),
        ('alumno', '0002_alumno_ramos'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inscripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inscripcion', models.DateField(auto_now_add=True)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alumno.alumno')),
                ('ramo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formularioRamos.ramos')),
            ],
        ),
    ]
