# Generated by Django 4.2.6 on 2023-11-18 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formularioRamos', '0003_ramos_profesor'),
        ('alumno', '0003_inscripcion_alter_alumno_ramos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alumno',
            name='ramos',
        ),
        migrations.AddField(
            model_name='alumno',
            name='nuevas_ramos',
            field=models.ManyToManyField(related_name='alumnos_nuevos', through='alumno.Inscripcion', to='formularioRamos.ramos'),
        ),
    ]
