# Generated by Django 4.2.6 on 2023-11-18 22:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alumno', '0005_rename_nuevas_ramos_alumno_inscripciones'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inscripcion',
            options={'verbose_name_plural': 'Inscribir'},
        ),
        migrations.RenameField(
            model_name='alumno',
            old_name='inscripciones',
            new_name='nuevas_ramos',
        ),
    ]
